logging:
  level:
    org.springframework.security: DEBUG
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 100MB
  application:
    name: springDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
server:
  port: ${MYSQL_PORT}
  servlet:
    session:
      timeout: 1h
jwt:
  base-key: ${JWT_HMAC_KEY}
  expiration-time: ${JWT_EXP_TIME}
  refresh-time: ${JWT_REF_TIME}
  refresh-limit: ${JWT_REF_LIMIT}
mypath:
  root-path: ${MY_ROOT_PATH}